version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ahorroplusia-db
    restart: always
    environment:
      POSTGRES_DB: ahorroplusia        # nombre de la base de datos
      POSTGRES_USER: postgres          # usuario
      POSTGRES_PASSWORD: 123456        # contrase√±a
    ports:
      - "5432:5432"                    # expone el puerto local:contenedor
    networks:
      - ahorroplus-network

networks:
  ahorroplus-network:
    driver: bridge
